Artschi feat tests random helper
TriNext/framework-util pull request #39
Opened 2024-01-17 13:02 UTC by TriNextArtschi

just do it

2024-01-19 10:42 UTC, TriNextErik commented
Scheitert an Coverage

2024-01-29 15:35 UTC, TriNextDennis requested changes

2024-01-29 15:35 UTC, TriNextDennis commented on src/test/java/test/de/framework/util/RandomHelperTest.java
> +        // TODO: Was wenn min > max?
TODO

2024-01-29 15:35 UTC, TriNextDennis commented on src/test/java/test/de/framework/util/RandomHelperTest.java
> +        // TODO: Negative Werte?
TODO

2024-01-30 14:38 UTC, merged